# Generated by Django 3.1.4 on 2020-12-23 21:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('timeofMatch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('encrypt_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championId', models.CharField(max_length=50)),
                ('championName', models.CharField(max_length=50)),
                ('champLevel', models.CharField(max_length=50)),
                ('win', models.CharField(max_length=50)),
                ('kills', models.CharField(max_length=50)),
                ('deaths', models.CharField(max_length=50)),
                ('assists', models.CharField(max_length=50)),
                ('totalMinionsKilled', models.CharField(max_length=50)),
                ('goldEarned', models.CharField(max_length=50)),
                ('spell1', models.CharField(max_length=50)),
                ('spell2', models.CharField(max_length=50)),
                ('encrypt_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerName', models.CharField(max_length=30)),
            ],
        ),
    ]
