# Generated by Django 3.1.4 on 2020-12-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypt_id', models.CharField(max_length=50)),
                ('streakLength', models.CharField(max_length=10)),
                ('typeofStreak', models.CharField(max_length=10)),
            ],
        ),
    ]
